![image.png]()

**Task - 1 Create a pandas dataframe (DataFrame name as 'df') (10 observation and 5 features)**

In [2]:
import pandas as pd
import numpy as np

In [6]:
d={'Name':['Sreenu','Rani','Sravan','Priya','Ajay','Suresh','Sita','Vijay','Ankit','Arpit'],
   'Age':[20,15,20,26,23,16,19,28,23,24],
   'Salary':[2000000,4000000,590000,np.nan,4560000,4520000,np.nan,2000000,np.nan,1000000],
   'Gender':['M','F','M','F','M','M','F','M','M','M'],
   'Place':['Govada','Kazipeta','Tenali','Tenali','Hyderabad','Chennai','Vellore','Banglore','Amritsar','Tejpur']}
print(d)

{'Name': ['Sreenu', 'Rani', 'Sravan', 'Priya', 'Ajay', 'Suresh', 'Sita', 'Vijay', 'Ankit', 'Arpit'], 'Age': [20, 15, 20, 26, 23, 16, 19, 28, 23, 24], 'Salary': [2000000, 4000000, 590000, nan, 4560000, 4520000, nan, 2000000, nan, 1000000], 'Gender': ['M', 'F', 'M', 'F', 'M', 'M', 'F', 'M', 'M', 'M'], 'Place': ['Govada', 'Kazipeta', 'Tenali', 'Tenali', 'Hyderabad', 'Chennai', 'Vellore', 'Banglore', 'Amritsar', 'Tejpur']}

In [7]:
df=pd.DataFrame(d)
print(df)

     Name  Age     Salary Gender      Place
0  Sreenu   20  2000000.0      M     Govada
1    Rani   15  4000000.0      F   Kazipeta
2  Sravan   20   590000.0      M     Tenali
3   Priya   26        NaN      F     Tenali
4    Ajay   23  4560000.0      M  Hyderabad
5  Suresh   16  4520000.0      M    Chennai
6    Sita   19        NaN      F    Vellore
7   Vijay   28  2000000.0      M   Banglore
8   Ankit   23        NaN      M   Amritsar
9   Arpit   24  1000000.0      M     Tejpur

**Task- 2 Check the info of 'df'**

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   Salary  7 non-null      float64
 3   Gender  10 non-null     object
 4   Place   10 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 528.0+ bytes

**Task 3- Check the descriptive statistics of 'df'**

In [9]:
df.describe()

             Age        Salary
count  10.000000  7.000000e+00
mean   21.400000  2.667143e+06
std     4.168666  1.672151e+06
min    15.000000  5.900000e+05
25%    19.250000  1.500000e+06
50%    21.500000  2.000000e+06
75%    23.750000  4.260000e+06
max    28.000000  4.560000e+06

**Task 4- check the 4th index observation with 'loc' slicing operator.**

In [10]:
df.loc[4]

Name           Ajay
Age              23
Salary    4560000.0
Gender            M
Place     Hyderabad
Name: 4, dtype: object

**Task 5 - Check the null values in your 'df'**

In [18]:
print(df.isnull().any())
print("-------------------------------------------")
df.isnull().sum()

Name      False
Age       False
Salary     True
Gender    False
Place     False
dtype: bool
-------------------------------------------

Name      0
Age       0
Salary    3
Gender    0
Place     0
dtype: int64